name: Fetch latest journal feeds (3-day window)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */2 * * *'  # 每 2 小时刷新一次（UTC）
    - cron: '0 0 * * *'     # 每天 08:00（Asia/Taipei, UTC+8）
    - cron: '10 4 * * *'    # 每天 12:10（Asia/Taipei, UTC+8）
    - cron: '0 16 * * *'    # 每天 00:00（Asia/Taipei, UTC+8

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser httpx

      - name: Build data
        run: |
          python scripts/build.py

      - name: Commit & push if changed
        shell: bash
        run: |
          set -e
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(data): update articles.json"
          git push
